<?php

namespace test;

include_once "../controller.php";

use PHPUnit\Framework\TestCase;



class testDbConnector extends TestCase
{
    //region private attributes

    //endregion private attributes

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }



    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
